name: lettutor
description: Lettutor.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter


  cupertino_icons: ^1.0.2

  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  flag: ^7.0.0
  video_player: ^2.8.2
  expandable_text: 2.3.0
  country_picker: ^2.0.21
  multi_dropdown: ^2.1.0
  pdfx:
    git:
      url: 'https://github.com/ScerIO/packages.flutter'
      ref: '4be9de9ffed5398fd7d5f44bbb07dcd3d3f1711b'
      path: packages/pdfx
  http: ^1.1.0
  dio: ^5.3.3
  flutter_riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  go_router: ^12.1.1
  json_annotation: ^4.8.1
  omni_datetime_picker: ^1.0.9
  easy_date_timeline: ^1.0.2
  infinite_scroll_pagination: ^4.0.0
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  universal_html: ^2.2.4
  js: ^0.6.7
  url_launcher: ^6.2.3
  intl: any
  flutter_localization: ^0.2.0
  file_picker: ^6.1.1
  flutter_chat_ui: ^1.6.10
  jitsi_meet_wrapper: ^0.2.0+1
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.3+2
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

  # Paid Packet
#  syncfusion_flutter_pdfviewer: ^23.1.42

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.6
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.4
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: google_fonts/Poppins-Thin.ttf
          weight: 100
        - asset: google_fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: google_fonts/Poppins-Light.ttf
          weight: 300
        - asset: google_fonts/Poppins-Regular.ttf
          weight: 400
        - asset: google_fonts/Poppins-Medium.ttf
          weight: 500
        - asset: google_fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: google_fonts/Poppins-Bold.ttf
          weight: 700
        - asset: google_fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: google_fonts/Poppins-Black.ttf
          weight: 900

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/lettutor.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/lettutor.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"