
import 'package:flag/flag.dart';

const mobileWidth = 600;
const titleWidth = 1050;
const sampleText = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, '
    'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. '
    'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut '
    'aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in '
    'voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint '
    'occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit '
    'anim id est laborum.';
final emailValidator = RegExp(
    r'^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$');

String meetingUrl = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb250ZXh0Ijp7InVzZXIiOnsiZW1haWwiOiJzdHVkZW50QGxldHR1dG9yLmNvbSIsIm5hbWUiOiJSb25hbGRvIn19LCJyb29tIjoiZjU2OWMyMDItN2JiZi00NjIwLWFmNzctZWNjMTQxOWE2YjI4LTRkNTRkM2Q3LWQyYTktNDJlNS05N2EyLTVlZDM4YWY1Nzg5YSIsInJvb21OYW1lIjoiZjU2OWMyMDItN2JiZi00NjIwLWFmNzctZWNjMTQxOWE2YjI4LTRkNTRkM2Q3LWQyYTktNDJlNS05N2EyLTVlZDM4YWY1Nzg5YSIsInVzZXJDYWxsIjp7ImlkIjoiZjU2OWMyMDItN2JiZi00NjIwLWFmNzctZWNjMTQxOWE2YjI4IiwiZW1haWwiOiJzdHVkZW50QGxldHR1dG9yLmNvbSIsIm5hbWUiOiJSb25hbGRvIiwiYXZhdGFyIjoiaHR0cHM6Ly9zYW5kYm94LmFwaS5sZXR0dXRvci5jb20vYXZhdGFyL2Y1NjljMjAyLTdiYmYtNDYyMC1hZjc3LWVjYzE0MTlhNmIyOGF2YXRhcjE3MDUzNzYzNzk5MDcucG5nIiwiY291bnRyeSI6IkFudGlndWEgYW5kIEJhcmJ1ZGEiLCJwaG9uZSI6Ijg0MjQ5OTk5NjUwOCIsImxhbmd1YWdlIjoiQWxiYW5pYW4iLCJiaXJ0aGRheSI6IjE5OTktMDYtMTUiLCJpc0FjdGl2YXRlZCI6dHJ1ZSwicmVxdWlyZU5vdGUiOiJtb25kYXksIHR1ZXNkYXkiLCJsZXZlbCI6IlBST0ZJQ0lFTkNZIiwiaXNQaG9uZUFjdGl2YXRlZCI6dHJ1ZSwidGltZXpvbmUiOjcsInN0dWR5U2NoZWR1bGUiOiJ0ZXN0IHNjaGVkdWxlICIsImNhblNlbmRNZXNzYWdlIjpmYWxzZX0sInVzZXJCZUNhbGxlZCI6eyJpZCI6IjRkNTRkM2Q3LWQyYTktNDJlNS05N2EyLTVlZDM4YWY1Nzg5YSIsImVtYWlsIjoidGVhY2hlckBsZXR0dXRvci5jb20iLCJuYW1lIjoiS2VlZ2FuIiwiYXZhdGFyIjoiaHR0cHM6Ly9zYW5kYm94LmFwaS5sZXR0dXRvci5jb20vYXZhdGFyLzRkNTRkM2Q3LWQyYTktNDJlNS05N2EyLTVlZDM4YWY1Nzg5YWF2YXRhcjE2ODQ0ODQ4NzkxODcuanBnIiwiY291bnRyeSI6IlROIiwicGhvbmUiOiI4NDM1NjAzMDg2NjU4NTYiLCJsYW5ndWFnZSI6IlVrcmFpbmlhbiIsImJpcnRoZGF5IjoiMTk5OS0wNi0wMSIsImlzQWN0aXZhdGVkIjp0cnVlLCJ0dXRvckluZm8iOnsiaWQiOiI2Y2E1YzA5Mi03NmVhLTRlNzItOWM2ZS0wNWUyMjM5YWEzM2IiLCJ1c2VySWQiOiI0ZDU0ZDNkNy1kMmE5LTQyZTUtOTdhMi01ZWQzOGFmNTc4OWEiLCJ2aWRlbyI6Imh0dHBzOi8vYXBpLmFwcC5sZXR0dXRvci5jb20vdmlkZW8vNGQ1NGQzZDctZDJhOS00MmU1LTk3YTItNWVkMzhhZjU3ODlhdmlkZW8xNjI3OTEzMDE1ODcxLm1wNCIsImJpbyI6IkkgYW0gcGFzc2lvbmF0ZSBhYm91dCBydW5uaW5nIGFuZCBmaXRuZXNzLCBJIG9mdGVuIGNvbXBldGUgaW4gdHJhaWwvbW91bnRhaW4gcnVubmluZyBldmVudHMgYW5kIEkgbG92ZSBwdXNoaW5nIG15c2VsZi4gSSBhbSB0cmFpbmluZyB0byBvbmUgZGF5IHRha2UgcGFydCBpbiB1bHRyYS1lbmR1cmFuY2UgZXZlbnRzLiBJIGFsc28gZW5qb3kgd2F0Y2hpbmcgcnVnYnkgb24gdGhlIHdlZWtlbmRzLCByZWFkaW5nIGFuZCB3YXRjaGluZyBwb2RjYXN0cyBvbiBZb3V0dWJlLiBNeSBtb3N0IG1lbW9yYWJsZSBsaWZlIGV4cGVyaWVuY2Ugd291bGQgYmUgbGl2aW5nIGluIGFuZCB0cmF2ZWxpbmcgYXJvdW5kIFNvdXRoZWFzdCBBc2lhLiIsImVkdWNhdGlvbiI6IkJBIiwiZXhwZXJpZW5jZSI6IkkgaGF2ZSBtb3JlIHRoYW4gMTAgeWVhcnMgb2YgdGVhY2hpbmcgZW5nbGlzaCBleHBlcmllbmNlIiwicHJvZmVzc2lvbiI6IkVuZ2xpc2ggdGVhY2hlciIsImFjY2VudCI6bnVsbCwidGFyZ2V0U3R1ZGVudCI6IkFkdmFuY2VkIiwiaW50ZXJlc3RzIjoiIEkgbG92ZWQgdGhlIHdlYXRoZXIsIHRoZSBzY2VuZXJ5IGFuZCB0aGUgbGFpZC1iYWNrIGxpZmVzdHlsZSBvZiB0aGUgbG9jYWxzLiIsImxhbmd1YWdlcyI6ImVuIiwic3BlY2lhbHRpZXMiOiJidXNpbmVzcy1lbmdsaXNoLGNvbnZlcnNhdGlvbmFsLWVuZ2xpc2gsZW5nbGlzaC1mb3Ita2lkcyxpZWx0cyxzdGFydGVycyxtb3ZlcnMsZmx5ZXJzLGtldCxwZXQsdG9lZmwsdG9laWMiLCJyZXN1bWUiOm51bGwsInJhdGluZyI6NC4xNzk2NDA3MTg1NjI4NzQsImlzQWN0aXZhdGVkIjp0cnVlLCJpc05hdGl2ZSI6bnVsbCwieW91dHViZVZpZGVvSWQiOm51bGwsImNyZWF0ZWRBdCI6IjIwMjEtMDgtMDJUMTQ6MDM6MzYuMzIwWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDEtMTdUMTQ6MjQ6NTIuODgwWiJ9LCJyZXF1aXJlTm90ZSI6bnVsbCwibGV2ZWwiOiJISUdIRVJfQkVHSU5ORVIiLCJpc1Bob25lQWN0aXZhdGVkIjpudWxsLCJ0aW1lem9uZSI6Nywic3R1ZHlTY2hlZHVsZSI6Ikdvb2QgbHVjayB0byB5b3UgYWxsIiwiY2FuU2VuZE1lc3NhZ2UiOmZhbHNlfSwiaXNUdXRvciI6ZmFsc2UsInN0YXJ0VGltZSI6MTcwNTUxNDQwMDAwMCwiZW5kU2Vzc2lvbiI6MTcwNTUxNTkwMDAwMCwidGltZUluUm9vbSI6MTgwMCwiYm9va2luZ0lkIjoiNTRmY2ViYjItMDI3Yy00YTMzLTk2MDEtMzU4ZWU0YWU5YTY4IiwiaWF0IjoxNzA1NTA1NTU3LCJleHAiOjE3MDU1MzAyOTksImF1ZCI6ImxpdmV0dXRvciIsImlzcyI6ImxpdmV0dXRvciIsInN1YiI6Imh0dHBzOi8vbWVldC50dXRvcmluZy5sZXRzdHVkeS5pbyJ9.OrVxTD4zGAxa-FjgWyxx1qrW_9rv6WnGuSlIzTiTRvc";

class Countries{
  static Map<String, String> countries = {
    "AF": "Afghanistan",
    "AX": "Aland Islands",
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarctica",
    "AG": "Antigua and Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BA": "Bosnia and Herzegovina",
    "BW": "Botswana",
    "BV": "Bouvet Island",
    "BR": "Brazil",
    "VG": "British Virgin Islands",
    "IO": "British Indian Ocean Territory",
    "BN": "Brunei Darussalam",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CV": "Cape Verde",
    "KY": "Cayman Islands",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "HK": "Hong Kong, SAR China",
    "MO": "Macao, SAR China",
    "CX": "Christmas Island",
    "CC": "Cocos (Keeling) Islands",
    "CO": "Colombia",
    "KM": "Comoros",
    "CG": "Congo (Brazzaville)",
    "CD": "Congo, (Kinshasa)",
    "CK": "Cook Islands",
    "CR": "Costa Rica",
    "CI": "Côte d'Ivoire",
    "HR": "Croatia",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "ET": "Ethiopia",
    "FK": "Falkland Islands (Malvinas)",
    "FO": "Faroe Islands",
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GF": "French Guiana",
    "PF": "French Polynesia",
    "TF": "French Southern Territories",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GG": "Guernsey",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Heard and Mcdonald Islands",
    "VA": "Holy See (Vatican City State)",
    "HN": "Honduras",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran, Islamic Republic of",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IM": "Isle of Man",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "JP": "Japan",
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KP": "Korea (North)",
    "KR": "Korea (South)",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Lao PDR",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libya",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MK": "Macedonia, Republic of",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexico",
    "FM": "Micronesia, Federated States of",
    "MD": "Moldova",
    "MC": "Monaco",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MS": "Montserrat",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Netherlands",
    "AN": "Netherlands Antilles",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MP": "Northern Mariana Islands",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestinian Territory",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PN": "Pitcairn",
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RE": "Réunion",
    "RO": "Romania",
    "RU": "Russian Federation",
    "RW": "Rwanda",
    "BL": "Saint-Barthélemy",
    "SH": "Saint Helena",
    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "MF": "Saint-Martin (French part)",
    "PM": "Saint Pierre and Miquelon",
    "VC": "Saint Vincent and Grenadines",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome and Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "GS": "South Georgia and the South Sandwich Islands",
    "SS": "South Sudan",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SJ": "Svalbard and Jan Mayen Islands",
    "SZ": "Swaziland",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syrian Arab Republic (Syria)",
    "TW": "Taiwan, Republic of China",
    "TJ": "Tajikistan",
    "TZ": "Tanzania, United Republic of",
    "TH": "Thailand",
    "TL": "Timor-Leste",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": "Turks and Caicos Islands",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States of America",
    "UM": "US Minor Outlying Islands",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela (Bolivarian Republic)",
    "VN": "Viet Nam",
    "VI": "Virgin Islands, US",
    "WF": "Wallis and Futuna Islands",
    "EH": "Western Sahara",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
  };
  static String alpha2ToCountryName(String alpha2Code){
    // A map of country names and their alpha2 codes
    return countries[alpha2Code] ?? 'Unknown';
  }

}