# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Lettutor
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.7'
        channel: 'stable'
    - run: flutter --version
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
        
    - run: flutter packages run build_runner build --delete-conflicting-outputs
    - name: Build apk
      working-directory: ./Lettutor
      run: flutter build apk
    - run: flutter build appbundle    
    - uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: build/app/outputs/apk/release/app-release.apk
