# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: WEB RELEASE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Lettutor
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.7'
        channel: 'stable'
    - run: flutter --version
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Get package
      run: flutter pub get

    - name: Build runner
      run: flutter packages run build_runner build --delete-conflicting-outputs
    - name: Build web
      run: flutter build web --release --base-href '/Advanced-Mobile/'
    - name: Push to Releases
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./Lettutor/build/web
        
